name       : natron
version    : 2.3.0
release    : 2
source     :
    - git|https://github.com/MrKepzie/Natron.git : 2.3.0
    - https://github.com/MrKepzie/OpenColorIO-Configs/archive/Natron-v2.3.tar.gz : da489d2c943beeb84ded33c7ae5f3c5728675d4667b685cec812f1caa49391fd
license    : GPL-2.0
homepage   : http://www.natron.fr
component  : multimedia.video
summary    : Open-source Node-graph based compositing software
description: |
    Open-source compositing software. Node-graph based. Similar in functionalities to Adobe After Effects and Nuke by The Foundry.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pyside)
    - pkgconfig(QtCore)
    - pkgconfig(shiboken)
    - libboost-devel
rundeps    :
    - openfx-arena
    - openfx-io
    - openfx-misc
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-usr-share-OFX-directory.patch
    mkdir OpenColorIO-Configs
    tar xf $sources/Natron-v*.tar.gz -C OpenColorIO-Configs --strip-components=1
    cp $pkgfiles/config.pri $workdir/config.pri
    sed -i 's/libcairo.a/libcairo.so/g' global.pri
    sed -i '1s/^/QMAKE_CXXFLAGS += -std=c++98\n/' Gui/Gui.pro
    sed -i '1s/^/QMAKE_CXXFLAGS += -std=c++98\n/' Engine/Engine.pro
    sed -i '1s/^/QMAKE_CXXFLAGS += -std=c++98\n/' Tests/Tests.pro

    %qmake4 PREFIX=$installdir/usr \
        CONFIG+=release
build      : |
    %make
install    : |
    %make_install
